// components/PythonRunner.tsx
'use client'

import { useEffect, useRef, useState } from 'react'
import { PyodideRunner, RunResult, RunnerStatus } from '@/lib/pyodide/runner'

interface Props {
  code?: string
  readonly?: boolean
  autorun?: boolean
}

export function PythonRunner({ code: initialCode = '', readonly = false, autorun = false }: Props) {
  const [code, setCode] = useState(initialCode)
  const [status, setStatus] = useState<RunnerStatus>('idle')
  const [result, setResult] = useState<RunResult | null>(null)
  const runner = useRef(PyodideRunner.getInstance())

  useEffect(() => {
    const unsubscribe = runner.current.onStatusChange(setStatus)
    runner.current.load()
    return unsubscribe
  }, [])

  useEffect(() => {
    if (autorun && status === 'ready') {
      handleRun()
    }
  }, [status, autorun])

  async function handleRun() {
    const res = await runner.current.run(code)
    setResult(res)
  }

  function handleStop() {
    runner.current.interrupt()
  }

  const isLoading = status === 'loading'
  const isRunning = status === 'running'
  const isReady = status === 'ready'

  return (
    <div className="python-runner">
      <textarea
        value={code}
        onChange={e => setCode(e.target.value)}
        readOnly={readonly}
        rows={8}
        spellCheck={false}
        style={{
          width: '100%',
          fontFamily: 'Menlo, Consolas, "Courier New", monospace',
          fontSize: '0.9rem',
          lineHeight: 1.6,
          padding: '0.75rem',
          borderRadius: '0.375rem',
          border: '1px solid var(--x-color-neutral-200, #e5e5e5)',
          background: 'var(--x-color-neutral-100, #f5f5f5)',
          color: 'inherit',
          resize: 'vertical',
          boxSizing: 'border-box',
        }}
      />
      <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginTop: '0.5rem' }}>
        <button
          onClick={handleRun}
          disabled={!isReady || isRunning}
          style={{ cursor: isReady ? 'pointer' : 'not-allowed' }}
        >
          {isRunning ? 'Running…' : '▶ Run'}
        </button>
        {isRunning && (
          <button onClick={handleStop}>■ Stop</button>
        )}
        <span style={{ fontSize: '0.8rem', opacity: 0.5 }}>
          {status === 'idle' && ''}
          {status === 'loading' && 'Loading Python…'}
          {status === 'ready' && 'Ready'}
          {status === 'running' && 'Running…'}
          {status === 'error' && 'Failed to load Python'}
        </span>
      </div>
      {result && (
        <div style={{
          marginTop: '0.75rem',
          padding: '0.75rem',
          borderRadius: '0.375rem',
          border: '1px solid var(--x-color-neutral-200, #e5e5e5)',
          background: 'var(--x-color-neutral-100, #f5f5f5)',
          color: 'inherit',
          fontFamily: 'Menlo, Consolas, "Courier New", monospace',
          fontSize: '0.9rem',
          whiteSpace: 'pre-wrap',
        }}>
          {result.stdout && <div>{result.stdout}</div>}
          {result.stderr && <div style={{ color: 'orange' }}>{result.stderr}</div>}
          {result.error && <div style={{ color: 'red' }}>{result.error}</div>}
          {!result.stdout && !result.stderr && !result.error && (
            <div style={{ opacity: 0.4 }}>No output</div>
          )}
        </div>
      )}
    </div>
  )
}

// slides/components/PythonRunner.vue
<template>
  <div class="python-runner">
    <textarea
      v-model="code"
      :readonly="readonly"
      rows="8"
      spellcheck="false"
      style="width: 100%; font-family: Menlo, Consolas, 'Courier New', monospace; font-size: 0.9rem; line-height: 1.6; padding: 0.75rem; border-radius: 0.375rem; border: 1px solid #e5e5e5; background: #fafafa; resize: vertical; box-sizing: border-box;"
    />
    <div style="display: flex; align-items: center; gap: 0.5rem; margin-top: 0.5rem;">
      <button @click="handleRun" :disabled="!isReady || isRunning">
        {{ isRunning ? 'Running…' : '▶ Run' }}
      </button>
      <button v-if="isRunning" @click="handleStop">■ Stop</button>
      <span style="font-size: 0.8rem; opacity: 0.5;">
        <template v-if="status === 'loading'">Loading Python…</template>
        <template v-else-if="status === 'ready'">Ready</template>
        <template v-else-if="status === 'running'">Running…</template>
        <template v-else-if="status === 'error'">Failed to load Python</template>
      </span>
    </div>
    <div v-if="result" style="margin-top: 0.75rem; padding: 0.75rem; border-radius: 0.375rem; border: 1px solid #e5e5e5; background: #fafafa; font-family: Menlo, Consolas, 'Courier New', monospace; font-size: 0.9rem; white-space: pre-wrap;">
      <div v-if="result.stdout">{{ result.stdout }}</div>
      <div v-if="result.stderr" style="color: orange;">{{ result.stderr }}</div>
      <div v-if="result.error" style="color: red;">{{ result.error }}</div>
      <div v-if="!result.stdout && !result.stderr && !result.error" style="opacity: 0.4;">No output</div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { PyodideRunner, RunResult, RunnerStatus } from '../../lib/pyodide/runner'

const props = withDefaults(defineProps<{
  code?: string
  readonly?: boolean
  autorun?: boolean
}>(), {
  code: '',
  readonly: false,
  autorun: false,
})

const code = ref(props.code)
const status = ref<RunnerStatus>('idle')
const result = ref<RunResult | null>(null)
const runner = PyodideRunner.getInstance()

const isReady = computed(() => status.value === 'ready')
const isRunning = computed(() => status.value === 'running')

let unsubscribe: (() => void) | null = null

onMounted(() => {
  unsubscribe = runner.onStatusChange(s => { status.value = s })
  runner.load()
})

onUnmounted(() => {
  unsubscribe?.()
})

async function handleRun() {
  result.value = await runner.run(code.value)
}

function handleStop() {
  runner.interrupt()
}
</script>
